site_name: SQUAD战术小队中文维基
site_author: Squad-CN-Wiki
copyright: "Copyright &copy; 2022-2023 SquadWiki-CN Team"
repo_url: https://github.com/AP54/SquadWiki-CN
edit_uri: edit/main/docs/

nav:
  - "HOME":
    - "Getting Started": "./index.md" 
    - "关于本项目": "./Intro/About.md"
    - "投喂": "./Intro/Support.md"
    - "致谢": "./Intro/Thanks.md"
  - "游戏教程":
    - "教程简介": "./Course/index.md"
    - "萌新入门":
      - "第一目 设置和UI": "./Course/Beginner/Chapter_1.md"
      - "第二目 特装和武器": "./Course/Beginner/Chapter_2.md"
      - "第三目 团队和社区": "./Course/Beginner/Chapter_3.md"
      - "第四目 战斗技巧": "./Course/Beginner/Chapter_4.md"
      - "第五目 载具识别": "./Course/Beginner/Chapter_5.md"
      - "第六目 索敌技巧": "./Course/Beginner/Chapter_6.md"
      - "第七目 规则和模式": "./Course/Beginner/Chapter_7.md"
    - "队长指挥技术":
      - "请求火力支援": "./Course/SquadLeader/Request_Fire_Support.md"
    - "模式规则":
      - "模式简介": "./Course/Gamemode/index.md"
      - "AAS | 攻守有序": "./Course/Gamemode/AAS.md"
      - "Destruction | 摧毁": "./Course/Gamemode/Destruction.md"
      - "Insurgency | 叛乱": "./Course/Gamemode/Insurgency.md"
      - "Invasion | 侵攻": "./Course/Gamemode/Invasion.md"
      - "RAAS | 随机攻守": "./Course/Gamemode/RAAS.md"
      - "Seed | 暖服": "./Course/Gamemode/Seed.md"
      - "Skirmish | 遭遇战": "./Course/Gamemode/Skirmish.md"
      - "Tanks | 载具大战": "./Course/Gamemode/Tanks.md"
      - "TA | 精准打击": "./Course/Gamemode/TA.md"
      - "TC | 领土控制": "./Course/Gamemode/TC.md"
      - "Training | 训练": "./Course/Gamemode/Training.md"
  - "SPLC": 
    - "战术小队中国顶级联赛": "./Contest/index.md"
    - "联赛赛程": "./Contest/SPLC/schedule.md"
  - "地图手册":
    - "地图手册": "./Map/index.md"
    - "暖服推荐": "./Map/Seeding.md"
    - "Al Basrah | 巴士拉": "./Map/Al_Basrah.md"
    - "Anvil | 铁砧": "./Map/Anvil.md"
    - "Belaya Pass | 贝拉亚山口": "./Map/Belaya_Pass.md"
    - "Black Coast | 黑色海岸": "./Map/Black_Coast.md"
    - "Chora | 乔拉": "./Map/Chora.md"
    - "Fallujah | 费卢杰": "./Map/Fallujah.md"
    - "Fool's Road | 傻瓜之路": "./Map/Fools_Road.md"
    - "Goose Bay | 鹅湾": "./Map/Goose_Bay.md"
    - "Gorodok | 格鲁多克": "./Map/Gorodok.md"
    - "Harju | 哈留" : "./Map/Harju.md"
    - "Jensen's Range | 延森训练场": "./Map/Jensens_Range.md"
    - "Kamdesh Highlands | 卡姆德什高地": "./Map/Kamdesh_Highlands.md"
    - "Kohat Toi | 科哈特": "./Map/Kohat_Toi.md"
    - "Kokan | 寇坎": "./Map/Kokan.md"
    - "Lashkar Valley | 拉什卡谷": "./Map/Lashkar_Valley.md"
    - "Logar Valley | 罗杰尔谷": "./Map/Logar_Valley.md"
    - "Manicouagan | 曼尼古根": "./Map/Manicouagan.md"
    - "Mestia | 梅斯提亚": "./Map/Mestia.md"
    - "Mutaha | 穆塔哈": "./Map/Mutaha.md"
    - "Narva | 纳尔瓦": "./Map/Narva.md"
    - "Pacific Proving Grounds | 太平洋训练场": "./Map/Pacific_Proving_Grounds.md"
    - "Skorpo | 斯科珀": "./Map/Skorpo.md"
    - "Sumari Bala | 索马里": "./Map/Sumari_Bala.md"
    - "Tallil Outskirts | 塔利尔郊区": "./Map/Tallil_Outskirts.md"
    - "Yehorivka | 叶霍里符卡": "./Map/Yehorivka.md"
  - "更新信息":
    - "战术小队版本V4.3更新日志": "./Update/v4.3/release_notes/index.md"
  - "运维管理":
    - "运维管理简介": "./Server/index.md"
    - "服务端管理":
      - "服务端安装": "./Server/Installation.md"
    - "控制命令":
      - "控制命令简介": "./Server/Command/index.md"
      - "公共命令": "./Server/Command/Public.md"
      - "管理命令": "./Server/Command/Admin.md"
      - "摄影命令": "./Server/Command/Camera.md"
      - "载具生成命令": "./Server/Command/Vehicle.md"
      - "部署物生成命令": "./Server/Command/Deployable.md"
  - "入驻组织":
    - "入驻组织列表": "./Union/index.md"
    - "[BY] 北域": "./Union/BY/index.md"
    - "[CHPD] 修仙公会": "./Union/CHPD/index.md"
    - "[CRN] 坎特洛特": "./Union/CRN/index.md"
    - "[DRN] 龙城战队": "./Union/DRN/index.md"
    - "[MAG] MAG社团": "./Union/MAG/index.md"
    - "[NMB] 北急熊战队": "./Union/NMB/index.md"
    - "[77] 萌新兄弟连": "./Union/77/index.md"
    - "=小鹿= 小鹿社团": "./Union/XL/index.md"    

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.superfences

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - content.code.copy
    - tabs: true
  palette:
    scheme: slate
    primary: deep purple
    accent: deep purple
  static_templates:
    - 404.html
  language: 'zh'
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
    repo: fontawesome/brands/github
  logo: logo/SQ_200_200.png
  favicon: logo/SQ_200_200.png
  plugins:
    - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       width: 100%
       height: auto
       zoomable: true
       draggable: true
    - search:
        lang: jp

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - Scripts/JavaScripts/tablesort.js


# extra_css:
#   - Scripts/CSS/background.css