[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"

[[redirects]]
  from = "/map/manic-5"
  to = "/map/manicouagan"
  status = 301

[[redirects]]
  from = "/GameMode/index.md"
  to = "/gamemode"
  status = 301