[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    SameSite = "None"
    Secure = "true"

[[headers]]
  for = "/beginner/enclosure/%E8%BD%BD%E5%85%B7%E8%AF%86%E5%88%AB%E6%89%8B%E5%86%8C-%E6%88%98%E6%9C%AF%E5%B0%8F%E9%98%9F%E4%B8%AD%E6%96%87%E7%BB%B4%E5%9F%BA.pdf"
  [headers.values]
    Content-Disposition = "attachment"

[[headers]]
  for = "/server/scripts/update.bat"
  [headers.values]
    Content-Disposition = "attachment"

[[redirects]]
  from = "/map/manic-5"
  to = "/map/manicouagan"
  status = 301

[[redirects]]
  from = "/command"
  to = "/server/command"
  status = 301

[[redirects]]
  from = "/command/public"
  to = "/server/command/public"
  status = 301

[[redirects]]
  from = "/command/admin"
  to = "/server/command/admin"
  status = 301

[[redirects]]
  from = "/command/camera"
  to = "/server/command/camera"
  status = 301

[[redirects]]
  from = "/command/vehicle"
  to = "/server/command/vehicle"
  status = 301

[[redirects]]
  from = "/command/deployable"
  to = "/server/command/deployable"
  status = 301