[[headers]]
  for="/beginner/enclosure/%E8%BD%BD%E5%85%B7%E8%AF%86%E5%88%AB%E6%89%8B%E5%86%8C-%E6%88%98%E6%9C%AF%E5%B0%8F%E9%98%9F%E4%B8%AD%E6%96%87%E7%BB%B4%E5%9F%BA.pdf"
  [headers.values]
    Content-Disposition = "attachment"
  for="/server/scripts/update.bat"
  [headers.values]
    Content-Disposition = "attachment"
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"